[theme]
base="dark"
 
[cookie]
expiry_days = 1
key = "csd"
name = "csdashboard"
 
[credentials]
usernames = {maadhusri = {email = "maadhusriusa@gmail.com", name = "Maadhusri", password = "$2b$12$WhHO9C/B9.ZsZguCpwijpeoI2LhY1qPz92VrYr.gA5Gc4wAGKiJz."}}

[preauthorized]
emails = ["maadhusriusa@gmail.com"]
